### ISSUE TITLE
Cookie not in host's domain error - Node

### ISSUE THREAD

**Issue by wiazur** [Azure-Samples/cognitive-services-content-moderator-samples#9]
### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Run the Human Reviews example with createReview() and getReview() functions in Node.

### Any log messages given by the failure
> Cookie not in this host's domain. Cookie:reviewservice.azurewebsites.net Request:westus.api.cognitive.microsoft.com
Getting review details after human review...
(node:15832) UnhandledPromiseRejectionWarning: Error: reviewId cannot be null or undefined.
    at Serializer.serialize (C:\Users\v-wiazur\Desktop\Content Moderator\content_moderator_quickstart - Node\node_modules\@azure\ms-rest-js\dist\msRest.node.js:508:19)
    at getOperationArgumentValueFromParameterPath (C:\Users\v-wiazur\Desktop\Content Moderator\content_moderator_quickstart - Node\node_modules\@azure\ms-rest-js\dist\msRest.node.js:3595:24)
    at getOperationArgumentValueFromParameter (C:\Users\v-wiazur\Desktop\Content Moderator\content_moderator_quickstart - Node\node_modules\@azure\ms-rest-js\dist\msRest.node.js:3570:12)
    at ContentModeratorClient.ServiceClient.sendOperationRequest (C:\Users\v-wiazur\Desktop\Content Moderator\content_moderator_quickstart - Node\node_modules\@azure\ms-rest-js\dist\msRest.node.js:3371:45)
    at Reviews.getReview (C:\Users\v-wiazur\Desktop\Content Moderator\content_moderator_quickstart - Node\node_modules\@azure\cognitiveservices-contentmoderator\dist\cognitiveservices-contentmoderator.js:3958:32)
    at Timeout.setTimeout [as _onTimeout] (C:\Users\v-wiazur\Desktop\Content Moderator\content_moderator_quickstart - Node\human_reviews.js:127:35)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
(node:15832) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:15832) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Expected/desired behavior
> It should return the review results, but does not. The review DOES get created, I am able to go to the website to review, but then processing it back in the code does not work.

### OS and Version?
> 
Windows 10, Version 10.0.18362 Build 18362

### Mention any other details that might be useful
I thought it was the Tough-cookie library not using the correct update (when I download the content moderator library it does not grab the most current versions of ms-rest-js and tough-cookie libraries). But a colleague is able to run this without getting the cookie error. I filed a ticket with support though, and the tech DID get the cookie error.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wiazur** [comment]
Looks like this was resolved with an update from the **msRest** library.
